### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by koravski** [geniegeist/unstable-card-game#1]
It shows only the wallpaper and nothing else. Your Heroku deployment also is not working. What is the problem?

**Comment by geniegeist** [comment]
Hey there, how come you are interested in this project? 

https://unstable-team42.herokuapp.com/:gameId/:numPlayer/:playerId

For example
https://unstable-team42.herokuapp.com/randomid/5/0

**Comment by koravski** [comment]
I like the game and found it. Now I understand how it works. Great. Good job.

**Comment by geniegeist** [comment]
Great. Be prepared to find many bugs though. The game has been hacked together during a weekend and is very unpolished.
